//========= Copyright (c) Valve Corporation, All rights reserved. ============//
//
// Purpose:
//
// $NoKeywords: $
//=============================================================================
#ifdef _WIN32
#pragma once
#endif

enum MATERIAL_FILE_TYPE
{
	MATERIAL_FILE_BASETEXTURE,
	MATERIAL_FILE_NORMAL,
	MATERIAL_FILE_PHONGEXPONENT,
	MATERIAL_FILE_SELFILLUM,
	NUM_MATERIAL_TEXTURE_FILE_TYPE
};

//-----------------------------------------------------------------------------
// Purpose: Import file dialog
//-----------------------------------------------------------------------------
class CTFFileImportDialog// : public vgui::Frame
{
public:
	enum BUILD_RESULT
	{
		BUILD_OKAY,
		BUILD_FAILED_NOSDK,
		BUILD_FAILED_NONAME,
		BUILD_FAILED_NOTYPE,
		BUILD_FAILED_NOMODELS,
		BUILD_FAILED_LODCOUNTMISMATCH,
		BUILD_FAILED_NOMATERIALS,
		BUILD_FAILED_MATERIALCOUNTMISMATCH,
		BUILD_FAILED_NOBACKPACKICON,
		BUILD_FAILED_BADNAME,
		BUILD_FAILED_BADTFENGLISHNAME,
		BUILD_FAILED_BADTYPE,
		BUILD_FAILED_BADMODEL,
		BUILD_FAILED_BADMATERIALTYPE,
		BUILD_FAILED_BADMATERIAL,
		BUILD_FAILED_MATERIALMISSINGSHADER,
		BUILD_FAILED_MATERIALMISSINGCLOAK,
		BUILD_FAILED_MATERIALMISSINGBURNING,
		BUILD_FAILED_MATERIALMISSINGJARATE,
		BUILD_FAILED_MATERIALMISSINGPAINTABLE,
		BUILD_FAILED_MISSINGMODEL,
		BUILD_FAILED_NEEDMORELOD,
		BUILD_FAILED_COMPLEXMODEL,
		BUILD_FAILED_BADIMAGE,
		BUILD_FAILED_COMPILE,
		BUILD_FAILED_NO_WORKSHOP_ID,
		BUILD_FAILED_IMAGEUNSUPPORTEDFILETYPE,
		BUILD_FAILED_IMAGERESOLUTIONNOTPOWEROF2,
		BUILD_FAILED_IMAGERESOLUTIONOVERLIMIT,
		BUILD_FAILED_NO_TAUNT_SOURCES,
		BUILD_FAILED_BAD_VCD_FILE,
		BUILD_FAILED_VCD_MISSING_EVENT_SEQUENCE,
		BUILD_FAILED_VCD_EVENT_SEQUENCE_TOO_LONG,

		NUM_BUILD_RESULTS
	};

	enum LOAD_RESULT
	{
		LOAD_OKAY,
		LOAD_FAILED,
		LOAD_FAILED_BADMODEL,
		LOAD_FAILED_COMPLEXMODEL,
		LOAD_FAILED_TOOMANYBONES,
		LOAD_FAILED_BADMATERIAL,
		LOAD_FAILED_TOOMANYMATERIALS,
		LOAD_FAILED_MATERIALCOUNTMISMATCH,
		LOAD_FAIL_ANIMATIONTOOLONG,
		NUM_LOAD_RESULTS
	};

	enum SAVE_RESULT
	{
		SAVE_OKAY,
		SAVE_FAILED,
		NUM_SAVE_RESULTS
	};

	enum BUILD_STAGE
	{
		BUILD_PREVIEW,
		BUILD_VERIFY,
		BUILD_FINAL
	};

	enum WARNING
	{
		WARNING_BASEALPHAMASK,
		NUM_WARNINGS
	};

	enum ImportPrefab_t
	{
		PREFAB_HAT = 0,
		PREFAB_MISC,
		PREFAB_TAUNT,

		PREFAB_COUNT
	};

	enum FileOpenMode 
	{
		FILE_OPEN_NONE,
		FILE_OPEN_LOAD,
		FILE_OPEN_SAVE,
		FILE_OPEN_ICON,
		FILE_OPEN_LOD0,
		FILE_OPEN_LOD1,
		FILE_OPEN_LOD2,
		FILE_OPEN_ANIMATION_SOURCE,
		FILE_OPEN_ANIMATION_VCD,
	};
};